### PR TITLE
Added and split some definitions

### PR DESCRIPTION
**Pull request by PeterBenko**
I took the liberty to split the index into applicable subfiles, hope that's OK.
Also added some classes, but there's still much to do

### CODE REVIEW

**Comment by JPAhnen** [comment]
Wow, great work!
Do your changes change the way it's imported? (I had not the time to try it yet).
I currently import fabric using `import * as fabric from "fabric";`

**Comment by PeterBenko** [comment]
The consumer would need to `import { fabric } from "fabric"` - this is consistent with latest @typings/fabric and I think the latest versions of fabric itself.

**Comment by JPAhnen** [comment]
I'm using fabric with the `aurelia-cli` with `requirejs`, and the way you mentioned doesn't work. But as far as I've read, some modules don't work very well with module loaders.
Since your definition seems to be correct, I have to use a small workaround to make it work for me:
```
import "fabric";
declare let fabric: any;
```

**Comment by JPAhnen** [comment]
I'm sorry, but somehow my test environment was in a bad shape.
After cleaning up, I don't get any import to work with your current definition. 
VS Code even doesn't find the type definition - if I move it over to  `@types\fabric` VS Code finds them, but I get other errors. 

The current version of `@types/fabric` does something similar to make `import { fabric } from "fabric"` works with their definition - and in this case I can do the `import` I mentioned in my last comment.

Do you have an idea what could cause this and what I could try?

**Comment by PeterBenko** [comment]
Hm, the small workaround doesn't seem that nice.
I have to admit that I've used the @types/fabric setup to do and test the typings. Currently, I still have them installed separately. 
A good starting point to include it in the project might be adding the `typings` property to the project's package.json. I didn't want to dive into that at that point... I guess now's the time.
a) We need to decide on a location where the typings should reside - I don't think they should be in `/dist` since it seems to be purely a build destination (set as default if no `-dist` param is present for build.js)
b) The _actual_ distribution bundle seems to be built with `export_*` scripts
c) The package.json `typings` entry needs to point to where the typings will be available in the end package

What are the other errors that you get if you move the typings to @types\fabric?

I'll try to look into it, but I'm going for a longer trip soon so I don't know when that will be...

**Comment by JPAhnen** [comment]
I'll create a simple example which you can clone so it's easier for both of us to find any problems...

**Comment by JPAhnen** [comment]
I created a simple example here: https://github.com/JPAhnen/demo-fabric

I finally found out why it didn't work - I put the typings into the `dist` folder, and Typescript doesn't seem to recognize them if they're in there. If `index.d.ts` is in `node_modules/fabric`  it works fine. So I'll merge your PR.

Also, maybe we should provide a script which merges all of your defintion files into a single file for deployment. What do you think?

**Pull request merged**
